name=WolfSense
version=1.0.0
author=Tony Huynh Tran
maintainer=Tony Huynh Tran <phuchunghuynhtran@gmail.com>
sentence=A high-performance library for BLE wireless game controller communication.
paragraph=WolfSense provides a fast and easy way for ESP32 to communicate with wireless game controllers (Flydigi Direwolf 3) via Bluetooth Low Energy (BLE), optimized for low latency.
category=Communication
url=https://github.com/Tony-Huynh-Tran/WolfSense
architectures=esp32